### ISSUE TITLE
Getting Html provider ready for release

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#506]
This is my "plan" for getting html provider in a ready for release state. Feel free to disagree with me on anything (included what I already pushed to the repo).
- Html types (HtmlDocument, HtmlElement, HtmlAttribute) and parsing (currently at https://github.com/fsharp/FSharp.Data/blob/HtmlTypeProvider/src/Html/HtmlParser.fs)
  - [x] Make sure parsing takes care of translating `&nbsp;`, char 160, and all entities seamlessly so the users don't need to think about it (#495)
  - [x] Ensure we can parse whatever HAP parses (bring over test cases from there)
  - [x] Add XML docs and fsx docs
- Html module with functions to navigate Html documents (currently at https://github.com/fsharp/FSharp.Data/blob/HtmlTypeProvider/src/Html/HtmlOperations.fs)
  - [x] Review and make sure we have a nice api (#472)
  - [ ] Make sure we handle inner text properly (HAP doesn't, that's why I needed this: https://github.com/ovatsus/Apps/blob/master/Common/HtmlAgilityPack.FSharp.fs#L78)
  - [x] Add XML docs and fsx docs (#472)
- Html table abstraction (currently at https://github.com/fsharp/FSharp.Data/blob/HtmlTypeProvider/src/Html/HtmlRuntime.fs)
  - [ ] Review if this should be internal only to the provider or should it be documented and presented to the user, similarly to the untyped CsvFile? In that case refactor so the api and implementation is closer.
- Html provider
  - [x] There's still some duplication with csv provider, refactor more
  - [ ] Improve fsx docs with more examples

/cc @tpetricek @forki @colinbull @mathias-brandewinder
