### ISSUE TITLE
FSharp.Formatting bugs affecting F# Data

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#698]
- [x] Extensions don't show - https://github.com/tpetricek/FSharp.Formatting/issues/156
- [ ] Invalid github links for type provider params - https://github.com/tpetricek/FSharp.Formatting/issues/153
- [ ] Invalid endline in github links - https://github.com/tpetricek/FSharp.Formatting/issues/154
- [x] Generic types not appearing correctly - https://github.com/tpetricek/FSharp.Formatting/issues/138
- [ ] Generate TOC https://github.com/tpetricek/FSharp.Formatting/issues/163
- [ ] A named param is confused with a toplevel value - https://github.com/tpetricek/FSharp.Formatting/issues/148
- [ ] Improve tooltips in the presence of <sumary> and other tags - https://github.com/tpetricek/FSharp.Formatting/issues/60
- [x] https://github.com/tpetricek/FSharp.Formatting/issues/199
- [x] https://github.com/tpetricek/FSharp.Formatting/issues/189
